import type {Metadata} from 'next'

export const metadata: Metadata = {
	title: 'Ваш профиль',
	description: 'Generated by create next app',
}

export default function LogLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <div>{children}</div>
}
