import {Metadata} from 'next'
import Table from '@/app/Components/Table/Table'
import Link from '../Components/Link/Link'
import {getCookiesOnTable} from '../Components/Table/actions'
import {permanentRedirect} from 'next/navigation'
import {paramsToUrl} from '@/Utils/url-search-params'
import {getAllUsers, User} from '@/Api'

const RoleToRu: Record<User['role'][number], string> = {
	ADMIN: 'Администратор',
	USER: 'Пользователь',
}

export const metadata: Metadata = {
	title: 'Найти пользователя',
	description: 'Generated by create next app',
}

export default async function Page({
	searchParams: {take, page},
}: {
	searchParams: {page: string; take: string}
}) {
	if (!take && !page) permanentRedirect(`/profile${paramsToUrl({page: 1, take: 5})}`)
	const data = (await getAllUsers(take, page)).map((v, idx) => ({
		id: (
			<Link prefetch={false} href={`/profile/${v.id}`}>
				{idx + 1}
			</Link>
		),
		email: v.email,
		role: v.role.map(v => RoleToRu[v]),
		rowId: idx,
	}))
	const title = 'Пользователи'
	const optionsTable = await getCookiesOnTable(title)
	return (
		<Table
			data={data}
			columns={[
				{key: 'id', displayName: 'Пользователь'},
				{key: 'email', displayName: 'Электронная почта'},
				{
					key: 'role',
					displayName: 'Роли',
				},
			]}
			optionsTable={optionsTable}
			title={title}
		/>
	)
}
