import {Metadata} from 'next'
import Table from '@/app/Components/Table/Table'
import Link from '../Components/Link/Link'
import {cookies} from 'next/headers'
import {getCookiesOnTable} from '../Components/Table/actions'
import {redirect} from 'next/navigation'
import {paramsToUrl} from '../../Utils/url-search-params'

type User = {
	id: React.JSX.Element
	email: string
	role: ['ADMIN', 'USER']
}

const RoleToRu: Record<User['role'][number], string> = {
	ADMIN: 'Администратор',
	USER: 'Пользователь',
}

export const metadata: Metadata = {
	title: 'Найти пользователя',
	description: 'Generated by create next app',
}

export default async function Page({
	searchParams: {take, page},
}: {
	searchParams: {page: string; take: string}
}) {
	if (!take && !page) redirect(`/profile${paramsToUrl({page: 1, take: 5})}`)
	const res = await fetch(
		`${process.env.API}/users/find-all${paramsToUrl({take, skip: `${(+page - 1) * +take}`})}`,
		{
			next: {revalidate: 5},
		},
	)
	if (!res.ok) throw Error()
	const data = ((await res.json()) as User[]).map((v, idx) => ({
		id: (
			<Link prefetch={false} href={`/profile/${v.id}`}>
				{idx + 1}
			</Link>
		),
		email: v.email,
		role: v.role.map(v => RoleToRu[v]),
		rowId: idx,
	}))
	const title = 'Пользователи'
	const optionsTable = await getCookiesOnTable(title)
	return (
		<Table
			data={data}
			columns={[
				{key: 'id', displayName: 'Пользователь'},
				{key: 'email', displayName: 'Электронная почта'},
				{
					key: 'role',
					displayName: 'Роли',
				},
			]}
			optionsTable={optionsTable}
			title={title}
		/>
	)
}
