import type {Metadata} from 'next'
import './globals.css'
import Header from './Components/Header/Header'
import Footer from './Components/Footer/Footer'
import StoreProvider from '@/Rtk/provider'
import AppNotification from './Components/AppNotification/AppNotification'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru">
			<StoreProvider>
				<body>
					<AppNotification />
					<Header />
					<main role="main">
						<div className="content">{children}</div>
					</main>
					<Footer />
				</body>
			</StoreProvider>
		</html>
	)
}
