import type {Metadata} from 'next'
import {Fragment} from 'react'

export const metadata: Metadata = {
	title: 'Сообщения',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <Fragment>{children}</Fragment>
}
