import type {Metadata} from 'next'
import styles from './log.module.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function LogLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <div className={styles.content}>{children}</div>
}
